"""
ToolAgent 适配器子包。

功能：
    收拢旧 state 到新 ToolAgent 契约的适配逻辑。
"""

from src.agents.tool_agent.adapters.registry_adapter import (
    TOOL_AGENT_TOOL_CATALOG_STATE_KEY,
    build_tool_agent_tool_catalog,
    build_tool_agent_tool_catalog_state_update,
    build_tool_agent_tool_catalog_state_update_with_mcp,
    build_tool_agent_tool_catalog_with_mcp,
    dump_tool_metadata_for_agent,
    get_registered_tool_metadata,
    list_registered_tool_metadata,
    merge_tool_catalog_items,
    merge_tool_metadata_items,
    tool_requires_confirmation,
)
from src.agents.tool_agent.adapters.runtime_adapter import (
    TOOL_AGENT_RUNTIME_RECORDS_STATE_KEY,
    build_failed_tool_result,
    build_runtime_call_id,
    build_tool_agent_runtime_state_update,
    dump_tool_agent_execution_records_for_state,
    execute_tool_call_with_runtime,
    execute_tool_calls_with_runtime,
    resolve_tool_source,
)
from src.agents.tool_agent.adapters.mcp_tool_schema_adapter import (
    build_mcp_tool_catalog_for_agent,
    build_tool_metadata_from_mcp_tool,
    build_tool_metadata_list_from_mcp_tools,
    dump_mcp_tool_metadata_for_agent,
)
from src.agents.tool_agent.adapters.tool_catalog_item_adapter import (
    MCP_TOOL_SOURCE,
    LOCAL_TOOL_SOURCE,
    build_tool_catalog_item_from_mcp_tool,
    build_tool_catalog_item_from_tool_metadata,
    build_tool_catalog_items_from_mcp_tools,
    build_tool_catalog_items_from_metadata,
    dump_tool_catalog_item_for_state,
    dump_tool_catalog_items_for_state,
)
from src.agents.tool_agent.adapters.tool_call_validation_adapter import (
    TOOL_CALL_VALIDATION_ERRORS_STATE_KEY,
    TOOL_CALL_VALIDATION_INVALID_CALLS_STATE_KEY,
    TOOL_CALL_VALIDATION_OK_STATE_KEY,
    TOOL_CALL_VALIDATION_SKIPPED_STATE_KEY,
    build_tool_call_validation_state_update,
    build_tool_catalog_by_name,
    build_validation_error,
    is_value_matching_json_schema_type,
    normalize_tool_call_for_validation,
    read_required_fields,
    read_schema_properties,
    validate_args_against_input_schema,
    validate_single_tool_call,
    validate_tool_calls_against_catalog,
    validate_tool_calls_from_state,
)
from src.agents.tool_agent.adapters.state_adapter import (
    TOOL_AGENT_RESPONSE_STATE_KEY,
    build_tool_agent_response_from_state,
    build_tool_agent_response_state_update,
    dump_tool_agent_response_for_state,
)

__all__ = [
    "TOOL_AGENT_RESPONSE_STATE_KEY",
    "TOOL_AGENT_RUNTIME_RECORDS_STATE_KEY",
    "TOOL_AGENT_TOOL_CATALOG_STATE_KEY",
    "TOOL_CALL_VALIDATION_ERRORS_STATE_KEY",
    "TOOL_CALL_VALIDATION_INVALID_CALLS_STATE_KEY",
    "TOOL_CALL_VALIDATION_OK_STATE_KEY",
    "TOOL_CALL_VALIDATION_SKIPPED_STATE_KEY",
    "LOCAL_TOOL_SOURCE",
    "MCP_TOOL_SOURCE",
    "build_tool_call_validation_state_update",
    "build_tool_catalog_by_name",
    "build_failed_tool_result",
    "build_mcp_tool_catalog_for_agent",
    "build_runtime_call_id",
    "build_tool_catalog_item_from_mcp_tool",
    "build_tool_catalog_item_from_tool_metadata",
    "build_tool_catalog_items_from_mcp_tools",
    "build_tool_catalog_items_from_metadata",
    "build_tool_metadata_from_mcp_tool",
    "build_tool_metadata_list_from_mcp_tools",
    "build_validation_error",
    "build_tool_agent_response_from_state",
    "build_tool_agent_response_state_update",
    "build_tool_agent_runtime_state_update",
    "build_tool_agent_tool_catalog",
    "build_tool_agent_tool_catalog_state_update",
    "build_tool_agent_tool_catalog_state_update_with_mcp",
    "build_tool_agent_tool_catalog_with_mcp",
    "dump_tool_agent_execution_records_for_state",
    "dump_tool_agent_response_for_state",
    "dump_mcp_tool_metadata_for_agent",
    "dump_tool_catalog_item_for_state",
    "dump_tool_catalog_items_for_state",
    "dump_tool_metadata_for_agent",
    "execute_tool_call_with_runtime",
    "execute_tool_calls_with_runtime",
    "get_registered_tool_metadata",
    "is_value_matching_json_schema_type",
    "list_registered_tool_metadata",
    "merge_tool_catalog_items",
    "merge_tool_metadata_items",
    "normalize_tool_call_for_validation",
    "read_required_fields",
    "read_schema_properties",
    "resolve_tool_source",
    "tool_requires_confirmation",
    "validate_args_against_input_schema",
    "validate_single_tool_call",
    "validate_tool_calls_against_catalog",
    "validate_tool_calls_from_state",
]
